/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuturo.gui;

import java.awt.*;
import javax.swing.*;
import com.formdev.flatlaf.themes.*;

/**
 *
 * @author Khelvin
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    boolean x = true;
    boolean theme = true;
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        topBarSettings = new javax.swing.JPanel();
        maximizeBtn = new javax.swing.JPanel();
        maximizeIcon = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitIcon = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JPanel();
        minimizeIcon = new javax.swing.JLabel();
        titleIcon = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        minimizedSideBar = new javax.swing.JPanel();
        hideshowmenu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        minimizedSpace = new javax.swing.JPanel();
        appearanceBtn = new javax.swing.JPanel();
        appearanceIcon = new javax.swing.JLabel();
        settingsBtn = new javax.swing.JPanel();
        settingsIcon = new javax.swing.JLabel();
        profileBtn = new javax.swing.JPanel();
        profileIcon = new javax.swing.JLabel();
        homeBtn = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        notesBtn = new javax.swing.JPanel();
        notesIcon = new javax.swing.JLabel();
        pointsBtn = new javax.swing.JPanel();
        pointsIcon = new javax.swing.JLabel();
        communityBtn = new javax.swing.JPanel();
        communityIcon = new javax.swing.JLabel();
        sidebarSeparator = new javax.swing.JSeparator();
        signOutBtn = new javax.swing.JPanel();
        signOutLbl = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        mainDashboard = new javax.swing.JTabbedPane();
        notesTab = new javax.swing.JPanel();
        notesSideBar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pointsTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        communityTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        profileTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        settingsTab = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        homeTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        topBar.setBackground(new java.awt.Color(0, 119, 204));
        topBar.setPreferredSize(new java.awt.Dimension(1280, 40));
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBarSettings.setBackground(new java.awt.Color(0, 119, 204));
        topBarSettings.setPreferredSize(new java.awt.Dimension(150, 50));
        topBarSettings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maximizeBtn.setBackground(new java.awt.Color(0, 119, 204));
        maximizeBtn.setPreferredSize(new java.awt.Dimension(50, 40));
        maximizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeBtnMouseClicked(evt);
            }
        });

        maximizeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximizeIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\maximize.png")); // NOI18N

        javax.swing.GroupLayout maximizeBtnLayout = new javax.swing.GroupLayout(maximizeBtn);
        maximizeBtn.setLayout(maximizeBtnLayout);
        maximizeBtnLayout.setHorizontalGroup(
            maximizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maximizeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maximizeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        maximizeBtnLayout.setVerticalGroup(
            maximizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maximizeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maximizeIcon)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        topBarSettings.add(maximizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        exitBtn.setBackground(new java.awt.Color(0, 119, 204));
        exitBtn.setPreferredSize(new java.awt.Dimension(50, 40));
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        exitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\close.png")); // NOI18N

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitIcon)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        topBarSettings.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        minimizeBtn.setBackground(new java.awt.Color(0, 119, 204));
        minimizeBtn.setPreferredSize(new java.awt.Dimension(50, 40));
        minimizeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeBtnMouseClicked(evt);
            }
        });

        minimizeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\minimize.png")); // NOI18N

        javax.swing.GroupLayout minimizeBtnLayout = new javax.swing.GroupLayout(minimizeBtn);
        minimizeBtn.setLayout(minimizeBtnLayout);
        minimizeBtnLayout.setHorizontalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minimizeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        minimizeBtnLayout.setVerticalGroup(
            minimizeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(minimizeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(minimizeIcon)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        topBarSettings.add(minimizeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        topBar.add(topBarSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1192, 0, -1, 40));

        titleIcon.setForeground(new java.awt.Color(0, 0, 0));
        titleIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\icon.png")); // NOI18N
        titleIcon.setPreferredSize(new java.awt.Dimension(50, 16));
        topBar.add(titleIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        getContentPane().add(topBar, java.awt.BorderLayout.PAGE_START);

        sideBar.setBackground(new java.awt.Color(116, 134, 186));
        sideBar.setPreferredSize(new java.awt.Dimension(250, 670));
        sideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizedSideBar.setBackground(new java.awt.Color(0, 119, 204));
        minimizedSideBar.setPreferredSize(new java.awt.Dimension(50, 680));
        minimizedSideBar.setLayout(new java.awt.BorderLayout());

        hideshowmenu.setBackground(new java.awt.Color(0, 119, 204));
        hideshowmenu.setForeground(new java.awt.Color(255, 255, 255));
        hideshowmenu.setMaximumSize(new java.awt.Dimension(50, 50));
        hideshowmenu.setPreferredSize(new java.awt.Dimension(50, 50));
        hideshowmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideshowmenuMouseClicked(evt);
            }
        });
        hideshowmenu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(153, 153, 153));
        menuIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/left-arrow.png"))); // NOI18N
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        hideshowmenu.add(menuIcon, java.awt.BorderLayout.CENTER);

        minimizedSpace.setBackground(new java.awt.Color(0, 119, 204));
        minimizedSpace.setPreferredSize(new java.awt.Dimension(50, 580));

        javax.swing.GroupLayout minimizedSpaceLayout = new javax.swing.GroupLayout(minimizedSpace);
        minimizedSpace.setLayout(minimizedSpaceLayout);
        minimizedSpaceLayout.setHorizontalGroup(
            minimizedSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        minimizedSpaceLayout.setVerticalGroup(
            minimizedSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        hideshowmenu.add(minimizedSpace, java.awt.BorderLayout.PAGE_END);

        minimizedSideBar.add(hideshowmenu, java.awt.BorderLayout.CENTER);

        appearanceBtn.setBackground(new java.awt.Color(0, 119, 204));
        appearanceBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        appearanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appearanceBtnMouseClicked(evt);
            }
        });
        appearanceBtn.setLayout(new java.awt.BorderLayout());

        appearanceIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appearanceIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\dark.png")); // NOI18N
        appearanceIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        appearanceBtn.add(appearanceIcon, java.awt.BorderLayout.CENTER);

        minimizedSideBar.add(appearanceBtn, java.awt.BorderLayout.PAGE_END);

        sideBar.add(minimizedSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        settingsBtn.setBackground(new java.awt.Color(116, 134, 186));
        settingsBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
        });

        settingsIcon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        settingsIcon.setForeground(new java.awt.Color(0, 0, 0));
        settingsIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\settings.png")); // NOI18N
        settingsIcon.setLabelFor(settingsBtn);
        settingsIcon.setText("Settings");
        settingsIcon.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout settingsBtnLayout = new javax.swing.GroupLayout(settingsBtn);
        settingsBtn.setLayout(settingsBtnLayout);
        settingsBtnLayout.setHorizontalGroup(
            settingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        settingsBtnLayout.setVerticalGroup(
            settingsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sideBar.add(settingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 200, -1));

        profileBtn.setBackground(new java.awt.Color(116, 134, 186));
        profileBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
        });

        profileIcon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        profileIcon.setForeground(new java.awt.Color(0, 0, 0));
        profileIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\profile.png")); // NOI18N
        profileIcon.setText("Profile");

        javax.swing.GroupLayout profileBtnLayout = new javax.swing.GroupLayout(profileBtn);
        profileBtn.setLayout(profileBtnLayout);
        profileBtnLayout.setHorizontalGroup(
            profileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        profileBtnLayout.setVerticalGroup(
            profileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sideBar.add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 200, -1));

        homeBtn.setBackground(new java.awt.Color(116, 134, 186));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeBtnMouseClicked(evt);
            }
        });

        homeIcon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        homeIcon.setForeground(new java.awt.Color(0, 0, 0));
        homeIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\home.png")); // NOI18N
        homeIcon.setText("Home");
        homeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homeBtnLayout = new javax.swing.GroupLayout(homeBtn);
        homeBtn.setLayout(homeBtnLayout);
        homeBtnLayout.setHorizontalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeBtnLayout.setVerticalGroup(
            homeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sideBar.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 200, 50));

        notesBtn.setBackground(new java.awt.Color(116, 134, 186));
        notesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notesBtnMouseClicked(evt);
            }
        });

        notesIcon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        notesIcon.setForeground(new java.awt.Color(0, 0, 0));
        notesIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\notes.png")); // NOI18N
        notesIcon.setText("Notes");

        javax.swing.GroupLayout notesBtnLayout = new javax.swing.GroupLayout(notesBtn);
        notesBtn.setLayout(notesBtnLayout);
        notesBtnLayout.setHorizontalGroup(
            notesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        notesBtnLayout.setVerticalGroup(
            notesBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(notesIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sideBar.add(notesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        pointsBtn.setBackground(new java.awt.Color(116, 134, 186));
        pointsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pointsBtnMouseClicked(evt);
            }
        });

        pointsIcon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        pointsIcon.setForeground(new java.awt.Color(0, 0, 0));
        pointsIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\points.png")); // NOI18N
        pointsIcon.setText("Points");

        javax.swing.GroupLayout pointsBtnLayout = new javax.swing.GroupLayout(pointsBtn);
        pointsBtn.setLayout(pointsBtnLayout);
        pointsBtnLayout.setHorizontalGroup(
            pointsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointsIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        pointsBtnLayout.setVerticalGroup(
            pointsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointsIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sideBar.add(pointsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        communityBtn.setBackground(new java.awt.Color(116, 134, 186));
        communityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                communityBtnMouseClicked(evt);
            }
        });

        communityIcon.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        communityIcon.setForeground(new java.awt.Color(0, 0, 0));
        communityIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khelvin\\Documents\\NetBeansProjects\\TuturoGUI\\src\\main\\resources\\images\\community.png")); // NOI18N
        communityIcon.setText("Community");

        javax.swing.GroupLayout communityBtnLayout = new javax.swing.GroupLayout(communityBtn);
        communityBtn.setLayout(communityBtnLayout);
        communityBtnLayout.setHorizontalGroup(
            communityBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communityBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(communityIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        communityBtnLayout.setVerticalGroup(
            communityBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(communityIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sideBar.add(communityBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        sidebarSeparator.setBackground(new java.awt.Color(83, 97, 138));
        sidebarSeparator.setForeground(new java.awt.Color(83, 97, 138));
        sideBar.add(sidebarSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 180, 10));

        signOutBtn.setBackground(new java.awt.Color(116, 134, 186));

        signOutLbl.setBackground(new java.awt.Color(0, 0, 0));
        signOutLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 11)); // NOI18N
        signOutLbl.setForeground(new java.awt.Color(0, 0, 0));
        signOutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signOutLbl.setText("Sign Out");
        signOutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout signOutBtnLayout = new javax.swing.GroupLayout(signOutBtn);
        signOutBtn.setLayout(signOutBtnLayout);
        signOutBtnLayout.setHorizontalGroup(
            signOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signOutBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signOutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        signOutBtnLayout.setVerticalGroup(
            signOutBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(signOutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        sideBar.add(signOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 200, 30));

        getContentPane().add(sideBar, java.awt.BorderLayout.LINE_START);

        dashboard.setBackground(new java.awt.Color(167, 184, 233));
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setPreferredSize(new java.awt.Dimension(1090, 680));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainDashboard.setForeground(new java.awt.Color(0, 119, 204));
        mainDashboard.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        notesTab.setBackground(new java.awt.Color(167, 184, 233));
        notesTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notesSideBar.setBackground(new java.awt.Color(167, 184, 233));
        notesSideBar.setMaximumSize(new java.awt.Dimension(2147483647, 720));
        notesSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Notes");
        notesSideBar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("create your notes here: ");
        notesSideBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jButton1.setText("New");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notesSideBar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 20));

        jButton2.setText("Open");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notesSideBar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 20));

        jButton3.setText("Delete");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        notesSideBar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 20));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Delete Note..");
        notesSideBar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 90, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Create Note..");
        notesSideBar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 90, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Open Note..");
        notesSideBar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, 20));

        notesTab.add(notesSideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 680));

        jPanel2.setBackground(new java.awt.Color(167, 184, 233));

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        notesTab.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 860, 680));

        mainDashboard.addTab("Notes", notesTab);

        pointsTab.setBackground(new java.awt.Color(167, 184, 233));

        jLabel3.setText("points");

        javax.swing.GroupLayout pointsTabLayout = new javax.swing.GroupLayout(pointsTab);
        pointsTab.setLayout(pointsTabLayout);
        pointsTabLayout.setHorizontalGroup(
            pointsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addContainerGap(1170, Short.MAX_VALUE))
        );
        pointsTabLayout.setVerticalGroup(
            pointsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pointsTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(647, Short.MAX_VALUE))
        );

        mainDashboard.addTab("Points", pointsTab);

        communityTab.setBackground(new java.awt.Color(167, 184, 233));

        jLabel4.setText("community");

        javax.swing.GroupLayout communityTabLayout = new javax.swing.GroupLayout(communityTab);
        communityTab.setLayout(communityTabLayout);
        communityTabLayout.setHorizontalGroup(
            communityTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communityTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(1142, Short.MAX_VALUE))
        );
        communityTabLayout.setVerticalGroup(
            communityTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communityTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(647, Short.MAX_VALUE))
        );

        mainDashboard.addTab("Community", communityTab);

        profileTab.setBackground(new java.awt.Color(167, 184, 233));

        jLabel5.setText("profile");

        javax.swing.GroupLayout profileTabLayout = new javax.swing.GroupLayout(profileTab);
        profileTab.setLayout(profileTabLayout);
        profileTabLayout.setHorizontalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(1170, Short.MAX_VALUE))
        );
        profileTabLayout.setVerticalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(644, Short.MAX_VALUE))
        );

        mainDashboard.addTab("Profile", profileTab);

        settingsTab.setBackground(new java.awt.Color(167, 184, 233));
        settingsTab.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("settiungs");
        settingsTab.add(jLabel6, java.awt.BorderLayout.CENTER);

        mainDashboard.addTab("Settings", settingsTab);

        homeTab.setBackground(new java.awt.Color(167, 184, 233));

        jLabel1.setText("home");

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(1165, Short.MAX_VALUE))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(640, Short.MAX_VALUE))
        );

        mainDashboard.addTab("Home", homeTab);

        dashboard.add(mainDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 710));

        getContentPane().add(dashboard, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hideshowmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideshowmenuMouseClicked
        if(x == true) {
            hideshowMenu(sideBar, x, menuIcon);
            SwingUtilities.updateComponentTreeUI(this);
            x = false;
        }
        else {
            hideshowMenu(sideBar, x, menuIcon);
            SwingUtilities.updateComponentTreeUI(this);
            x = true;
        }
    }//GEN-LAST:event_hideshowmenuMouseClicked
 
    private void maximizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeBtnMouseClicked
        if(this.getExtendedState() != MainGUI.MAXIMIZED_BOTH) {
            this.setExtendedState(MainGUI.MAXIMIZED_BOTH);
        }
        else {
            this.setExtendedState(MainGUI.NORMAL);
        }
    }//GEN-LAST:event_maximizeBtnMouseClicked

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitBtnMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        mainDashboard.setSelectedIndex(4);
    }//GEN-LAST:event_profileBtnMouseClicked

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        mainDashboard.setSelectedIndex(5);
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void appearanceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appearanceBtnMouseClicked
        // SET DARK/LIGHT MODE HERE (CHANGE WHOLE UI THEME HERE)
        if (theme == false) {
            changeAppearance(theme, appearanceIcon);
            theme = true;
        }
        else {
            changeAppearance(theme, appearanceIcon);
            theme = false;
        }
        
    }//GEN-LAST:event_appearanceBtnMouseClicked

    private void minimizeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeBtnMouseClicked
        if(this.getExtendedState() != MainGUI.ICONIFIED) {
            this.setExtendedState(MainGUI.ICONIFIED);
        }
        else {
            this.setExtendedState(MainGUI.NORMAL);
        }
    }//GEN-LAST:event_minimizeBtnMouseClicked

    private void homeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homeIconMouseClicked

    private void notesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesBtnMouseClicked
        mainDashboard.setSelectedIndex(1);
    }//GEN-LAST:event_notesBtnMouseClicked

    private void signOutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutLblMouseClicked
        int s = JOptionPane.showConfirmDialog(this, "Do yoy want to sign out?", "Sign Out?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (s == JOptionPane.OK_OPTION) {
            System.exit(0);
            // Papuntahin sa Login form 
            // iimport
        }
    }//GEN-LAST:event_signOutLblMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardMouseClicked

    private void homeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseClicked
        mainDashboard.setSelectedIndex(WIDTH);
    }//GEN-LAST:event_homeBtnMouseClicked

    private void pointsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pointsBtnMouseClicked
        mainDashboard.setSelectedIndex(2);
    }//GEN-LAST:event_pointsBtnMouseClicked

    private void communityBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_communityBtnMouseClicked
        mainDashboard.setSelectedIndex(3);
    }//GEN-LAST:event_communityBtnMouseClicked

    private void changeIcon(JLabel button, String image) {
        ImageIcon menuImage = new ImageIcon(getClass().getResource(image));
        button.setIcon(menuImage);
    }
    
    private void changeAppearance(boolean theme, JLabel button) {
        JFrame frame = new JFrame();
        if (theme == true) {
            // DARK MODE
            for (Component components : sideBar.getComponents()){
                if (components instanceof JPanel) {
                    JPanel panel = (JPanel) components;


                    homeTab.setBackground(new Color(34, 55, 117));
                    notesTab.setBackground(new Color(34, 55, 117));
                    pointsTab.setBackground(new Color(34, 55, 117));
                    communityTab.setBackground(new Color(34, 55, 117));
                    profileTab.setBackground(new Color(34, 55, 117));
                    settingsTab.setBackground(new Color(34, 55, 117));
                    sideBar.setBackground(new Color(42, 53, 84));
                    panel.setBackground(new Color(42, 53, 84));
                    minimizedSideBar.setBackground(new Color(0, 119,204));
                    
                    homeIcon.setForeground(Color.white);
                    notesIcon.setForeground(Color.white);
                    pointsIcon.setForeground(Color.white);
                    communityIcon.setForeground(Color.white);
                    profileIcon.setForeground(Color.white);
                    settingsIcon.setForeground(Color.white);
                    signOutLbl.setForeground(Color.white);
                    
                    sidebarSeparator.setForeground(new Color(29, 37, 59));
                    sidebarSeparator.setBackground(new Color(29, 37, 59));
                    
                    changeIcon(homeIcon, "/images/dark/light-home.png");
                    changeIcon(notesIcon, "/images/dark/light-notes.png");
                    changeIcon(pointsIcon, "/images/dark/light-points.png");
                    changeIcon(communityIcon, "/images/dark/light-community.png");
                    changeIcon(profileIcon, "/images/dark/light-profile.png");
                    changeIcon(settingsIcon, "/images/dark/light-settings.png");
                }
            }
            changeIcon(button, "/images/light/light.png");
        }
        else {
            // LIGHT MODE
            for (Component components : sideBar.getComponents()){
                if (components instanceof JPanel) {
                    JPanel panel = (JPanel) components;
//                    dashboard.setBackground(new Color(167, 184, 233));
//                    mainDashboard.setBackground(new Color(167, 184, 233));

                    homeTab.setBackground(new Color(167, 184, 233));
                    notesTab.setBackground(new Color(167, 184, 233));
                    pointsTab.setBackground(new Color(167, 184, 233));
                    communityTab.setBackground(new Color(167, 184, 233));
                    profileTab.setBackground(new Color(167, 184, 233));
                    settingsTab.setBackground(new Color(167, 184, 233));
                    sideBar.setBackground(new Color(116, 134, 186));
                    panel.setBackground(new Color(116, 134, 186));
                    minimizedSideBar.setBackground(new Color(0, 119,204));
                    
                    homeIcon.setForeground(Color.BLACK);
                    notesIcon.setForeground(Color.BLACK);
                    pointsIcon.setForeground(Color.BLACK);
                    communityIcon.setForeground(Color.BLACK);
                    profileIcon.setForeground(Color.BLACK);
                    settingsIcon.setForeground(Color.BLACK);
                    signOutLbl.setForeground(Color.BLACK);
                    
                    sidebarSeparator.setForeground(new Color(83, 97, 138));
                    sidebarSeparator.setBackground(new Color(83, 97, 138));
                    
                    changeIcon(homeIcon, "/images/light/home.png");
                    changeIcon(notesIcon, "/images/light/notes.png");
                    changeIcon(pointsIcon, "/images/light/points.png");
                    changeIcon(communityIcon, "/images/light/community.png");
                    changeIcon(profileIcon, "/images/light/profile.png");
                    changeIcon(settingsIcon, "/images/light/settings.png");
                }
            }
            changeIcon(button, "/images/light/dark.png");
        }
    }
    
    public void hideshowMenu(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true) {
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeIcon(button, "/images/light/hamburger.png");
        }
        else {
            menushowhide.setPreferredSize(new Dimension(250, menushowhide.getHeight()));
            changeIcon(button, "/images/light/left-arrow.png");
        }
    }
    
    private void notesClick(JPanel panel){
        mainDashboard.remove(this);
        mainDashboard.add(panel);
        mainDashboard.revalidate();
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appearanceBtn;
    private javax.swing.JLabel appearanceIcon;
    private javax.swing.JPanel communityBtn;
    private javax.swing.JLabel communityIcon;
    private javax.swing.JPanel communityTab;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JPanel hideshowmenu;
    private javax.swing.JPanel homeBtn;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JPanel homeTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTabbedPane mainDashboard;
    private javax.swing.JPanel maximizeBtn;
    private javax.swing.JLabel maximizeIcon;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JPanel minimizeBtn;
    private javax.swing.JLabel minimizeIcon;
    private javax.swing.JPanel minimizedSideBar;
    private javax.swing.JPanel minimizedSpace;
    private javax.swing.JPanel notesBtn;
    private javax.swing.JLabel notesIcon;
    private javax.swing.JPanel notesSideBar;
    private javax.swing.JPanel notesTab;
    private javax.swing.JPanel pointsBtn;
    private javax.swing.JLabel pointsIcon;
    private javax.swing.JPanel pointsTab;
    private javax.swing.JPanel profileBtn;
    private javax.swing.JLabel profileIcon;
    private javax.swing.JPanel profileTab;
    private javax.swing.JPanel settingsBtn;
    private javax.swing.JLabel settingsIcon;
    private javax.swing.JPanel settingsTab;
    private javax.swing.JPanel sideBar;
    private javax.swing.JSeparator sidebarSeparator;
    private javax.swing.JPanel signOutBtn;
    private javax.swing.JLabel signOutLbl;
    private javax.swing.JLabel titleIcon;
    private javax.swing.JPanel topBar;
    private javax.swing.JPanel topBarSettings;
    // End of variables declaration//GEN-END:variables
}
