/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuturo.gui;

import javax.swing.JOptionPane;
import tuturo.login.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.*;
import javax.swing.table.DefaultTableModel;
import tuturo.manager.SessionsManager;
import tuturo.manager.UsersManager;
import tuturo.model.Sessions;
import tuturo.othergui.AboutUsGUI;
import tuturo.othergui.NotesSearchFile;
import tuturo.othergui.TreeFileSystem;

/**
 *
 * @author Khelvin
 */
public class StudentGUI extends javax.swing.JFrame {
    SessionsManager ss = new SessionsManager();
    UsersManager um = new UsersManager();
    Statement statement;
    Connection conn;
    /**
     * Creates new form StudentGUI
     */
    public StudentGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentSidePanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        notesBtn = new javax.swing.JButton();
        communityBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        logoutPanel = new javax.swing.JPanel();
        logoutIcon = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        MainTabbedPane = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        homeSideBar = new javax.swing.JPanel();
        searchTutorBtn = new javax.swing.JButton();
        findSessionBtn = new javax.swing.JButton();
        todoListBtn = new javax.swing.JButton();
        welcomePanel = new javax.swing.JPanel();
        welcomeLbl = new javax.swing.JLabel();
        homeTabbedPanel = new javax.swing.JTabbedPane();
        searchTutorPane = new javax.swing.JScrollPane();
        availableSessions = new javax.swing.JTable();
        searchTutorTxt = new javax.swing.JTextField();
        searchTutorLbl = new javax.swing.JLabel();
        notesTab = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        openNotesBtn = new javax.swing.JButton();
        commTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        profileTab = new javax.swing.JPanel();
        welcomeProfileLbl = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profilePicture = new javax.swing.JPanel();
        editProfileBtn = new javax.swing.JButton();
        profileNameLbl = new javax.swing.JLabel();
        profileDetails = new javax.swing.JPanel();
        usernameLbl = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        realNameTxt = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        changePassLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        profileDetails2 = new javax.swing.JPanel();
        bioLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bioTxt = new javax.swing.JTextArea();
        addressLbl = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        accIDLbl = new javax.swing.JLabel();
        accIDHolder = new javax.swing.JLabel();
        saveProfileBtn = new javax.swing.JButton();
        discardProfileBtn = new javax.swing.JButton();
        dateJoinedLbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        settingsTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        aboutLbl = new javax.swing.JLabel();
        aboutBtn = new javax.swing.JButton();
        closePanel = new javax.swing.JPanel();
        closeIcon1 = new javax.swing.JLabel();
        settingsPanel = new javax.swing.JPanel();
        settingsIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        setName("mainFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark/light-home.png"))); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        notesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark/light-notes.png"))); // NOI18N
        notesBtn.setText("Notes");
        notesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        notesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesBtnActionPerformed(evt);
            }
        });

        communityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark/light-community.png"))); // NOI18N
        communityBtn.setText("Community");
        communityBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        communityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityBtnActionPerformed(evt);
            }
        });

        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark/light-profile.png"))); // NOI18N
        profileBtn.setText("Profile");
        profileBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });

        logoutIcon.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        logoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark/light-logout.png"))); // NOI18N
        logoutIcon.setText("Logout");

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout studentSidePanelLayout = new javax.swing.GroupLayout(studentSidePanel);
        studentSidePanel.setLayout(studentSidePanelLayout);
        studentSidePanelLayout.setHorizontalGroup(
            studentSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(communityBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(logoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        studentSidePanelLayout.setVerticalGroup(
            studentSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(communityBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileBtn)
                .addGap(488, 488, 488)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        getContentPane().add(studentSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 670));

        titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        titlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePanelMouseClicked(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        titleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        titleLbl.setText("Student");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        MainTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        MainTabbedPane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        MainTabbedPane.setToolTipText("");

        homeTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Home"));

        searchTutorBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchTutorBtn.setText("Show Open Sessions");
        searchTutorBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchTutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTutorBtnActionPerformed(evt);
            }
        });

        findSessionBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        findSessionBtn.setText("Search a Session");
        findSessionBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        findSessionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findSessionBtnActionPerformed(evt);
            }
        });

        todoListBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        todoListBtn.setText("To-Do List");
        todoListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout homeSideBarLayout = new javax.swing.GroupLayout(homeSideBar);
        homeSideBar.setLayout(homeSideBarLayout);
        homeSideBarLayout.setHorizontalGroup(
            homeSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTutorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(findSessionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todoListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        homeSideBarLayout.setVerticalGroup(
            homeSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTutorBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findSessionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(todoListBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        welcomePanel.setBackground(new java.awt.Color(132, 159, 255));

        welcomeLbl.setBackground(new java.awt.Color(51, 51, 51));
        welcomeLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(51, 51, 51));
        welcomeLbl.setText("Welcome, ");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(welcomeLbl)
                .addContainerGap())
        );

        searchTutorPane.setRowHeaderView(null);

        availableSessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tutor ID", "Tutor Name", "Sub ID", "Subject Name", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        availableSessions.setShowGrid(false);
        availableSessions.setShowVerticalLines(true);
        availableSessions.getTableHeader().setResizingAllowed(false);
        availableSessions.getTableHeader().setReorderingAllowed(false);
        searchTutorPane.setViewportView(availableSessions);
        if (availableSessions.getColumnModel().getColumnCount() > 0) {
            availableSessions.getColumnModel().getColumn(0).setPreferredWidth(30);
            availableSessions.getColumnModel().getColumn(0).setMaxWidth(30);
            availableSessions.getColumnModel().getColumn(1).setPreferredWidth(50);
            availableSessions.getColumnModel().getColumn(1).setMaxWidth(50);
            availableSessions.getColumnModel().getColumn(2).setResizable(false);
            availableSessions.getColumnModel().getColumn(2).setPreferredWidth(270);
            availableSessions.getColumnModel().getColumn(3).setPreferredWidth(30);
            availableSessions.getColumnModel().getColumn(3).setMaxWidth(30);
            availableSessions.getColumnModel().getColumn(4).setResizable(false);
            availableSessions.getColumnModel().getColumn(4).setPreferredWidth(270);
            availableSessions.getColumnModel().getColumn(5).setResizable(false);
            availableSessions.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        homeTabbedPanel.addTab("Open Sessions", searchTutorPane);

        searchTutorTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchTutorTxtKeyTyped(evt);
            }
        });

        searchTutorLbl.setText("Search Tutor:");

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addComponent(welcomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(homeTabLayout.createSequentialGroup()
                .addComponent(homeSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(searchTutorLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(homeTabbedPanel)))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchTutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTutorLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homeTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        MainTabbedPane.addTab("", homeTab);

        notesTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Notes"));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel7.setText("Notes");

        jLabel13.setText("Open your Notes");

        openNotesBtn.setText("Open");
        openNotesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openNotesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout notesTabLayout = new javax.swing.GroupLayout(notesTab);
        notesTab.setLayout(notesTabLayout);
        notesTabLayout.setHorizontalGroup(
            notesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(notesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notesTabLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addGap(838, 838, 838))
                    .addGroup(notesTabLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openNotesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        notesTabLayout.setVerticalGroup(
            notesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addGroup(notesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(openNotesBtn))
                .addContainerGap())
        );

        MainTabbedPane.addTab("", notesTab);

        commTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Community"));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel3.setText("Community");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1086, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel3);

        jButton8.setText("Post New Thread");

        jButton15.setText("Explore Communities");

        jButton16.setText("Notifications");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout commTabLayout = new javax.swing.GroupLayout(commTab);
        commTab.setLayout(commTabLayout);
        commTabLayout.setHorizontalGroup(
            commTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(commTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(commTabLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(commTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        commTabLayout.setVerticalGroup(
            commTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(commTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        MainTabbedPane.addTab("", commTab);

        profileTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile"));

        welcomeProfileLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        welcomeProfileLbl.setText("Hello, ");

        profilePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));

        profilePicture.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout profilePictureLayout = new javax.swing.GroupLayout(profilePicture);
        profilePicture.setLayout(profilePictureLayout);
        profilePictureLayout.setHorizontalGroup(
            profilePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        profilePictureLayout.setVerticalGroup(
            profilePictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        editProfileBtn.setText("Edit Profile");
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        profileNameLbl.setText("Name here");

        profileDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("User Information"));

        usernameLbl.setText("Username");

        usernameTxt.setEnabled(false);

        jLabel9.setText("Complete Name");

        realNameTxt.setEnabled(false);

        emailLbl.setText("Email");

        emailTxt.setEnabled(false);

        changePassLbl.setText("Password");

        jButton1.setText("Change Password");

        javax.swing.GroupLayout profileDetailsLayout = new javax.swing.GroupLayout(profileDetails);
        profileDetails.setLayout(profileDetailsLayout);
        profileDetailsLayout.setHorizontalGroup(
            profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(usernameLbl)
                    .addComponent(emailLbl)
                    .addComponent(changePassLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(usernameTxt)
                    .addComponent(realNameTxt)
                    .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addGap(380, 380, 380))
        );
        profileDetailsLayout.setVerticalGroup(
            profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(realNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profileDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePassLbl)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profileDetails2.setBorder(javax.swing.BorderFactory.createTitledBorder("Other Settings"));

        bioLbl.setText("Bio");

        bioTxt.setColumns(20);
        bioTxt.setLineWrap(true);
        bioTxt.setRows(5);
        bioTxt.setEnabled(false);
        jScrollPane3.setViewportView(bioTxt);

        addressLbl.setText("Address");

        addressTxt.setEnabled(false);

        accIDLbl.setText("Account ID");

        javax.swing.GroupLayout profileDetails2Layout = new javax.swing.GroupLayout(profileDetails2);
        profileDetails2.setLayout(profileDetails2Layout);
        profileDetails2Layout.setHorizontalGroup(
            profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDetails2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bioLbl)
                    .addComponent(addressLbl)
                    .addComponent(accIDLbl))
                .addGap(40, 40, 40)
                .addGroup(profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accIDHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profileDetails2Layout.setVerticalGroup(
            profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileDetails2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bioLbl)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileDetails2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(addressLbl))
                    .addGroup(profileDetails2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(profileDetails2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accIDLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accIDHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        saveProfileBtn.setText("Save Changes");
        saveProfileBtn.setEnabled(false);
        saveProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveProfileBtnMouseClicked(evt);
            }
        });
        saveProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProfileBtnActionPerformed(evt);
            }
        });

        discardProfileBtn.setText("Discard");
        discardProfileBtn.setEnabled(false);
        discardProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discardProfileBtnMouseClicked(evt);
            }
        });

        dateJoinedLbl.setText("date_created");

        jLabel14.setText("Date Created");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(profilePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(profilePanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(dateJoinedLbl))
                                    .addComponent(jLabel14))))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(profileDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileDetails2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(profileNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(discardProfileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveProfileBtn)
                .addGap(8, 8, 8))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profileDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(editProfileBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateJoinedLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profileDetails2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discardProfileBtn)
                    .addComponent(saveProfileBtn)))
        );

        javax.swing.GroupLayout profileTabLayout = new javax.swing.GroupLayout(profileTab);
        profileTab.setLayout(profileTabLayout);
        profileTabLayout.setHorizontalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(welcomeProfileLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        profileTabLayout.setVerticalGroup(
            profileTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeProfileLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("", profileTab);

        settingsTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        jLabel1.setText("General");

        jLabel2.setText("Setting 1");

        jLabel4.setText("Setting 2");

        jLabel5.setText("Setting 3");

        jLabel8.setText("Setting 4");

        jLabel10.setText("Setting 5");

        jLabel11.setText("Appearance");

        jLabel12.setText("Dark Theme");

        jButton2.setText("Save");

        aboutLbl.setText("About");

        aboutBtn.setText("About Us");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsTabLayout = new javax.swing.GroupLayout(settingsTab);
        settingsTab.setLayout(settingsTabLayout);
        settingsTabLayout.setHorizontalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5)
                    .addGroup(settingsTabLayout.createSequentialGroup()
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1)
                            .addComponent(aboutLbl))
                        .addGap(4, 4, 4)
                        .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(settingsTabLayout.createSequentialGroup()
                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8)
                                    .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)))
                                .addGap(30, 30, 30)
                                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(aboutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(873, 873, 873))
        );
        settingsTabLayout.setVerticalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jCheckBox5))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jCheckBox6))
                .addGap(40, 40, 40)
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboutLbl)
                    .addComponent(aboutBtn))
                .addGap(312, 312, 312)
                .addComponent(jButton2)
                .addContainerGap())
        );

        MainTabbedPane.addTab("", settingsTab);

        getContentPane().add(MainTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 1100, 670));

        closePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closePanelMouseClicked(evt);
            }
        });

        closeIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark/light-close.png"))); // NOI18N

        javax.swing.GroupLayout closePanelLayout = new javax.swing.GroupLayout(closePanel);
        closePanel.setLayout(closePanelLayout);
        closePanelLayout.setHorizontalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePanelLayout.createSequentialGroup()
                .addComponent(closeIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        closePanelLayout.setVerticalGroup(
            closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(closePanelLayout.createSequentialGroup()
                .addComponent(closeIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(closePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        settingsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsPanelMouseClicked(evt);
            }
        });

        settingsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark/light-settings.png"))); // NOI18N

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(settingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(settingsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(settingsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//     public void showSessions() {
//        SessionsManager sm = new SessionsManager(); 
//        ArrayList<Sessions> sessionList = sm.sList();
//        
//        DefaultTableModel model = (DefaultTableModel) availableSessions.getModel();
//        Object[] row = new Object[5];
//        model.setRowCount(0);
//        for (int i = 0; i < sessionList.size(); i++) {
//            row[0] = sessionList.get(i).sessionID;
//            row[1] = "000" + sessionList.get(i).hostID;
//            row[2] = sessionList.get(i).hostName;
//            row[3] = sessionList.get(i).subjectID;
//            row[4] = sessionList.get(i).subjectName;
//            model.addRow(row);
//        }
//    }
    
    private void communityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityBtnActionPerformed
        MainTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_communityBtnActionPerformed

    private void notesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesBtnActionPerformed
        MainTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_notesBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        MainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        MainTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void titlePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseClicked
        MainTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_titlePanelMouseClicked

    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
        usernameTxt.setEnabled(true);
        realNameTxt.setEnabled(true);
        emailTxt.setEnabled(true);
        saveProfileBtn.setEnabled(true);
        discardProfileBtn.setEnabled(true);

    }//GEN-LAST:event_editProfileBtnActionPerformed

    private void saveProfileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveProfileBtnMouseClicked
        
    }//GEN-LAST:event_saveProfileBtnMouseClicked

    private void discardProfileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discardProfileBtnMouseClicked
        usernameTxt.setEnabled(false);
        realNameTxt.setEnabled(false);
        emailTxt.setEnabled(false);
        saveProfileBtn.setEnabled(false);
        discardProfileBtn.setEnabled(false);
    }//GEN-LAST:event_discardProfileBtnMouseClicked

    private void saveProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProfileBtnActionPerformed
        String username = usernameTxt.getText();
        String realname = realNameTxt.getText();
        String email = emailTxt.getText();
        String accID = accIDHolder.getText();

        um.updateProfile(username, realname, email, accID);
        JOptionPane.showMessageDialog(null, "Profile Updated Successfully");

        usernameTxt.setEnabled(false);
        realNameTxt.setEnabled(false);
        emailTxt.setEnabled(false);
        saveProfileBtn.setEnabled(false);
        discardProfileBtn.setEnabled(false);
    }//GEN-LAST:event_saveProfileBtnActionPerformed

    private void closePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closePanelMouseClicked

    private void settingsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsPanelMouseClicked
        MainTabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_settingsPanelMouseClicked

    private void openNotesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openNotesBtnActionPerformed
        TreeFileSystem open = new TreeFileSystem();
        open.setVisible(true);
    }//GEN-LAST:event_openNotesBtnActionPerformed

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        int s = JOptionPane.showConfirmDialog(this, "Do you want to sign out?", "Sign Out?", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (s == JOptionPane.OK_OPTION) {
            setVisible(false);
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        AboutUsGUI aug = new AboutUsGUI();
        aug.setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void searchTutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTutorBtnActionPerformed
        homeTabbedPanel.setSelectedIndex(0);
        SessionsManager sm = new SessionsManager(); 
        ArrayList<Sessions> sessionList = sm.sesList();
        
        DefaultTableModel model = (DefaultTableModel) availableSessions.getModel();
        Object[] row = new Object[6];
        model.setRowCount(0);
        for (int i = 0; i < sessionList.size(); i++) {
            row[0] = sessionList.get(i).sessionID;
            row[1] = "000" + sessionList.get(i).hostID;
            row[2] = sessionList.get(i).hostName;
            row[3] = sessionList.get(i).subjectID;
            row[4] = sessionList.get(i).subjectName;
            row[5] = sessionList.get(i).date;
            model.addRow(row);
        }
    }//GEN-LAST:event_searchTutorBtnActionPerformed

    public void showSearchedItem(String search){
        SessionsManager sm = new SessionsManager();
        ArrayList<Sessions> searchList = sm.searchList(search);
        
        DefaultTableModel model = (DefaultTableModel) availableSessions.getModel();
        Object[] row = new Object[6];
        model.setRowCount(0);
        
        for (int i = 0; i < searchList.size(); i++) {
            row[0] = searchList.get(i).sessionID;
            row[1] = "000" + searchList.get(i).hostID;
            row[2] = searchList.get(i).hostName;
            row[3] = searchList.get(i).subjectID;
            row[4] = searchList.get(i).subjectName;
            row[5] = searchList.get(i).date;
            model.addRow(row);
        }
    }
    
    private void findSessionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findSessionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findSessionBtnActionPerformed

    private void searchTutorTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTutorTxtKeyTyped
        SessionsManager sm = new SessionsManager();
        ArrayList<Sessions> searchList = sm.searchList(searchTutorTxt.getText());
        
        DefaultTableModel model = (DefaultTableModel) availableSessions.getModel();
        Object[] row = new Object[6];
        model.setRowCount(0);
        
        for (int i = 0; i < searchList.size(); i++) {
            row[0] = searchList.get(i).sessionID;
            row[1] = "000" + searchList.get(i).hostID;
            row[2] = searchList.get(i).hostName;
            row[3] = searchList.get(i).subjectID;
            row[4] = searchList.get(i).subjectName;
            row[5] = searchList.get(i).date;
            model.addRow(row);
        }
    }//GEN-LAST:event_searchTutorTxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JButton aboutBtn;
    private javax.swing.JLabel aboutLbl;
    public javax.swing.JLabel accIDHolder;
    private javax.swing.JLabel accIDLbl;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTxt;
    public javax.swing.JTable availableSessions;
    private javax.swing.JLabel bioLbl;
    private javax.swing.JTextArea bioTxt;
    private javax.swing.JLabel changePassLbl;
    private javax.swing.JLabel closeIcon1;
    private javax.swing.JPanel closePanel;
    private javax.swing.JPanel commTab;
    private javax.swing.JButton communityBtn;
    public javax.swing.JLabel dateJoinedLbl;
    private javax.swing.JButton discardProfileBtn;
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JLabel emailLbl;
    public javax.swing.JTextField emailTxt;
    private javax.swing.JButton findSessionBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel homeSideBar;
    private javax.swing.JPanel homeTab;
    private javax.swing.JTabbedPane homeTabbedPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JButton notesBtn;
    private javax.swing.JPanel notesTab;
    private javax.swing.JButton openNotesBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JPanel profileDetails;
    private javax.swing.JPanel profileDetails2;
    public javax.swing.JLabel profileNameLbl;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel profilePicture;
    private javax.swing.JPanel profileTab;
    public javax.swing.JTextField realNameTxt;
    private javax.swing.JButton saveProfileBtn;
    private javax.swing.JButton searchTutorBtn;
    private javax.swing.JLabel searchTutorLbl;
    private javax.swing.JScrollPane searchTutorPane;
    private javax.swing.JTextField searchTutorTxt;
    private javax.swing.JLabel settingsIcon;
    private javax.swing.JPanel settingsPanel;
    private javax.swing.JPanel settingsTab;
    private javax.swing.JPanel studentSidePanel;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton todoListBtn;
    private javax.swing.JLabel usernameLbl;
    public javax.swing.JTextField usernameTxt;
    public javax.swing.JLabel welcomeLbl;
    private javax.swing.JPanel welcomePanel;
    public javax.swing.JLabel welcomeProfileLbl;
    // End of variables declaration//GEN-END:variables
}
