/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tuturo.login;

import tuturo.manager.UsersManager;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.sql.*;
import java.util.Enumeration;
import javax.swing.*;
import tuturo.database.*;
import tuturo.gui.MainGUI;

/**
 *
 * @author Khelvin
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterDBs
     */
    public RegisterForm() {
        initComponents();
        FlatMacDarkLaf.setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRole = new javax.swing.ButtonGroup();
        mainRegisterPanel = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        desc = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        fullNameLbl = new javax.swing.JLabel();
        phoneNoTxt = new javax.swing.JTextField();
        lastNameTxt = new javax.swing.JTextField();
        roleLbl = new javax.swing.JLabel();
        tutor = new javax.swing.JRadioButton();
        student = new javax.swing.JRadioButton();
        separator = new javax.swing.JSeparator();
        usernameLbl = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordTxt = new JPasswordField();
        buttonGroup = new javax.swing.JPanel();
        signInBtn = new javax.swing.JButton();
        signSLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");

        mainRegisterPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainRegisterPanel.setPreferredSize(new java.awt.Dimension(450, 475));
        mainRegisterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPanel.setBackground(new java.awt.Color(65, 65, 65));
        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desc.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        desc.setForeground(new java.awt.Color(153, 153, 153));
        desc.setText("Join us to connect and learn from tutors nearby. Sign up now");
        registerPanel.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 296, -1));

        welcomeLbl.setFont(new java.awt.Font("Yu Gothic UI", 1, 27)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(204, 204, 204));
        welcomeLbl.setText("Be Part of Tuturo Family");
        registerPanel.add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 310, 29));

        fullNameLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        fullNameLbl.setText("Full Name");
        registerPanel.add(fullNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        phoneNoTxt.setBackground(new java.awt.Color(65, 65, 65));
        phoneNoTxt.setForeground(new java.awt.Color(204, 204, 204));
        phoneNoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        registerPanel.add(phoneNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 150, 20));

        lastNameTxt.setBackground(new java.awt.Color(65, 65, 65));
        lastNameTxt.setForeground(new java.awt.Color(204, 204, 204));
        lastNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        registerPanel.add(lastNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 20));

        roleLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        roleLbl.setText("Are you a.. ?");
        registerPanel.add(roleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        groupRole.add(tutor);
        tutor.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        tutor.setText("Tutor");
        registerPanel.add(tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        groupRole.add(student);
        student.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        student.setText("Student");
        registerPanel.add(student, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));
        registerPanel.add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 300, 10));

        usernameLbl.setText("Username");
        registerPanel.add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        firstNameTxt.setBackground(new java.awt.Color(65, 65, 65));
        firstNameTxt.setForeground(new java.awt.Color(204, 204, 204));
        firstNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        registerPanel.add(firstNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 20));

        jLabel2.setText("Email and Phone No.");
        registerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        usernameTxt.setBackground(new java.awt.Color(65, 65, 65));
        usernameTxt.setForeground(new java.awt.Color(204, 204, 204));
        usernameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        registerPanel.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 20));

        emailTxt.setBackground(new java.awt.Color(65, 65, 65));
        emailTxt.setForeground(new java.awt.Color(204, 204, 204));
        emailTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        registerPanel.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 20));

        passwordLbl.setText("Password");
        registerPanel.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        passwordTxt.setBackground(new java.awt.Color(65, 65, 65));
        passwordTxt.setForeground(new java.awt.Color(204, 204, 204));
        passwordTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        registerPanel.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 310, 20));
        passwordTxt.putClientProperty(FlatClientProperties.STYLE, "" +
            "showRevealButton:true");

        buttonGroup.setBackground(new java.awt.Color(65, 65, 65));

        signInBtn.setBackground(new java.awt.Color(65, 65, 65));
        signInBtn.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(255, 255, 255));
        signInBtn.setText("Sign in");
        signInBtn.setBorder(null);
        signInBtn.setBorderPainted(false);
        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInBtnMouseClicked(evt);
            }
        });

        signSLbl.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        signSLbl.setForeground(new java.awt.Color(204, 204, 204));
        signSLbl.setText("Already have an account?");

        javax.swing.GroupLayout buttonGroupLayout = new javax.swing.GroupLayout(buttonGroup);
        buttonGroup.setLayout(buttonGroupLayout);
        buttonGroupLayout.setHorizontalGroup(
            buttonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGroupLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(signSLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signInBtn)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        buttonGroupLayout.setVerticalGroup(
            buttonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signSLbl)
                    .addComponent(signInBtn))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        registerPanel.add(buttonGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 310, 30));

        registerBtn.setText("Register");
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        registerPanel.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 310, -1));

        mainRegisterPanel.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 360, 440));
        registerPanel.putClientProperty(FlatClientProperties.STYLE, "" +
            "arc:40;");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseClicked
        setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_signInBtnMouseClicked

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        String FName = this.firstNameTxt.getText();
        String LName = this.lastNameTxt.getText();
        String fullName = FName +" "+ LName;
        String username = this.usernameTxt.getText();
        String email = this.emailTxt.getText();
        String phoneNo = this.phoneNoTxt.getText();
        String userRole = getSelectedButtonText(groupRole);
        String password = this.passwordTxt.getText();
        
        UsersManager user = new UsersManager();
        
        user.registerUser(fullName, username, phoneNo, email, userRole, password);
        setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_registerBtnMouseClicked
                      

    public String getSelectedButtonText(ButtonGroup groupRole) {
        for (Enumeration<AbstractButton> buttons = groupRole.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonGroup;
    private javax.swing.JLabel desc;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel fullNameLbl;
    private javax.swing.ButtonGroup groupRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JPanel mainRegisterPanel;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField phoneNoTxt;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton signInBtn;
    private javax.swing.JLabel signSLbl;
    private javax.swing.JRadioButton student;
    private javax.swing.JRadioButton tutor;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
